<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>13</LangVersion>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<OutputPath>../mod/newest/plugins</OutputPath>
		<PathMap>$(MSBuildProjectDirectory)=/$(SolutionName)</PathMap>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>portable</DebugType>
		<OutputPath>/home/cube/warpzone/rw/RainWorld_Data/StreamingAssets/mods/testiterator/plugins/</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
		<OutputPath>/home/cube/warpzone/rw/RainWorld_Data/StreamingAssets/mods/testiterator/plugins/</OutputPath>
		<Optimize>false</Optimize>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="../lib/*.dll">
			<Private>false</Private>
		</Reference>
		<Reference Include="$(RainWorldDir)/BepInEx/core/*.dll">
			<Private>false</Private>
		</Reference>
		<Reference Include="$(RainWorldDir)/BepInEx/plugins/*.dll">
			<Private>false</Private>
		</Reference>
		<Reference Include="$(RainWorldDir)/BepInEx/utils/*.dll">
			<Private>false</Private>
		</Reference>
		<Reference Include="$(RainWorldDir)/RainWorld_Data/Managed/Unity*.dll">
			<Private>false</Private>
		</Reference>
		<Reference Include="CWStuff">
		  <HintPath>..\..\..\.steam\steam\steamapps\workshop\content\312520\3232063592\newest\plugins\CWStuff.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="PolySharp" Version="1.15.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>
		
	<Target Name="GenerateMod" AfterTargets="PostBuildEvent" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<ItemGroup>
			<RemovePlugins Include="../mod/newest/plugins/*.pdb" />
		</ItemGroup>
				
		<Delete Files="@(RemovePlugins)" />
	</Target>

</Project>
